In [8]:
import pandas as pd
import numpy as np
import cv2
import tensorflow as tf
from tensorflow import keras
from keras.preprocessing.image import ImageDataGenerator

In [9]:
train_path = "data/train"
val_path = "data/val"
test_path = "data/test"

In [10]:
train_batch = ImageDataGenerator(preprocessing_function=tf.keras.applications.vgg16.preprocess_input).flow_from_directory(
    directory=train_path,target_size=(244,244),batch_size=10)
test_batch = ImageDataGenerator(preprocessing_function=tf.keras.applications.vgg16.preprocess_input).flow_from_directory(
    directory=test_path,target_size=(244,244),batch_size=10)
val_batch = ImageDataGenerator(preprocessing_function=tf.keras.applications.vgg16.preprocess_input).flow_from_directory(
    directory=val_path,target_size=(244,244),batch_size=10)


Found 5064 images belonging to 2 classes.
Found 1733 images belonging to 2 classes.
Found 755 images belonging to 2 classes.


In [11]:
vgg16_model = keras.applications.vgg16.VGG16()

In [12]:
model = keras.Sequential()
for layer in vgg16_model.layers[:-1]:
    model.add(layer)

In [13]:
for layer in model.layers:
    layer.trainable=False

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)      

In [15]:
model.add(keras.layers.Dense(1,activation="sigmoid"))

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)      

In [17]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [18]:
result=model.fit(train_batch,validation_data=val_batch,epochs=1,verbose=1 , batch_size = 64)

 14/507 [..............................] - ETA: 19:40 - loss: 0.8523 - accuracy: 0.5000

KeyboardInterrupt: 

In [12]:
result.history['accuracy']

[0.9842022061347961, 0.9970378875732422]

In [13]:
result.history['val_accuracy']

[0.9827814698219299, 0.9814569354057312]

In [14]:
model.evaluate(test_batch)

174/174 [==============================] - 448s 3s/step - loss: 0.0712 - accuracy: 0.9815


[0.07119984924793243, 0.9815348982810974]

In [3]:
from tensorflow.keras.models import load_model
#model.save("D:\project")


In [17]:
model = load_model("D:\project")

In [30]:

def preprocess_image(image_path):
    # Read the image
    image = cv2.imread(image_path)
    print(image)
    # Resize the image to match the input size of your model
    image = cv2.resize(image, (224, 224))
    # Preprocess the image (assuming you used VGG19 preprocess_input during training)
    image = image.astype('float32')
    image /= 255.0  # Normalize pixel values
    # Expand dimensions to create a batch of size 1
    image = np.expand_dims(image, axis=0)
    return image

In [31]:
model = load_model('D:\project')

In [40]:
def preprocess_image(image_path):
    # Read the image
    image = cv2.imread(image_path)
    print(image)
    # Resize the image to match the input size of your model
    image = cv2.resize(image, (224, 224))
    # Preprocess the image (assuming you used VGG19 preprocess_input during training)
    image = image.astype('float32')
    image /= 255.0  # Normalize pixel values
    # Expand dimensions to create a batch of size 1
    image = np.expand_dims(image, axis=0)
    return image
# Path to your test image
test_image_path = 'test.JPEG'

# Preprocess the test image
test_image = preprocess_image(test_image_path)

# Make predictions
prediction = model.predict(test_image)

# Convert prediction to a readable format (e.g., class labels)
class_index = np.argmax(prediction)
#if class_index > 0.5:
   # predicted_class = "Without Mask"
#else:
    #predicted_class = "With Mask"

print("Prediction:", class_index)


[[[132 137 136]
  [133 138 137]
  [134 139 138]
  ...
  [205 201 190]
  [205 201 190]
  [205 201 190]]

 [[133 138 137]
  [134 139 138]
  [135 140 139]
  ...
  [206 202 191]
  [206 202 191]
  [206 202 191]]

 [[135 140 139]
  [136 141 140]
  [137 142 141]
  ...
  [208 204 193]
  [207 203 192]
  [207 203 192]]

 ...

 [[ 49  70  92]
  [ 60  81 103]
  [ 73  94 116]
  ...
  [117 107  97]
  [116 106  96]
  [116 106  96]]

 [[ 44  65  87]
  [ 55  76  98]
  [ 68  89 111]
  ...
  [106  96  86]
  [106  96  86]
  [105  95  85]]

 [[ 41  62  84]
  [ 51  72  94]
  [ 65  86 108]
  ...
  [ 99  89  79]
  [ 99  89  79]
  [ 98  88  78]]]
1/1 [==============================] - 0s 281ms/step
Prediction: 0
